package com.wilson.cmpe272.service;

import com.wilson.cmpe272.entity.User;
import org.apache.commons.codec.binary.Base32;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.security.SecureRandom;
import java.time.LocalDateTime;
import java.util.Random;
import javax.crypto.Mac;
import javax.crypto.spec.SecretKeySpec;
import java.nio.ByteBuffer;

@Service
public class TwoFactorService {
    
    private static final Logger logger = LoggerFactory.getLogger(TwoFactorService.class);
    
    @Autowired
    private EmailService emailService;
    
    
    private final Random random = new Random();
    private final Base32 base32 = new Base32();
    
    public String generateVerificationCode() {
        String code = String.format("%06d", random.nextInt(1000000));
        logger.debug("Generated verification code: {}", code);
        return code;
    }
    
    public String generateSecretKey() {
        logger.debug("Generating secret key for authenticator app");
        byte[] buffer = new byte[10];
        new SecureRandom().nextBytes(buffer);
        String secretKey = base32.encodeToString(buffer).replaceAll("=", "");
        logger.debug("Secret key generated successfully");
        return secretKey;
    }
    
    public void sendEmailVerificationCode(User user) {
        logger.info("Sending email verification code to user: {}", user.getEmail());
        String verificationCode = generateVerificationCode();
        user.setEmailVerificationCode(verificationCode);
        user.setEmailVerificationExpiresAt(LocalDateTime.now().plusMinutes(10));
        
        emailService.sendVerificationCode(user.getEmail(), verificationCode);
        logger.info("Email verification code sent successfully to user: {}", user.getEmail());
    }
    
    
    public void sendTwoFactorCode(User user) {
        logger.info("Sending 2FA code for user: {} using method: {}", user.getEmail(), user.getTwoFactorMethod());
        String verificationCode = generateVerificationCode();
        
        switch (user.getTwoFactorMethod()) {
            case EMAIL:
                logger.info("Sending 2FA code via email to user: {}", user.getEmail());
                emailService.sendTwoFactorCode(user.getEmail(), verificationCode);
                user.setEmailVerificationCode(verificationCode);
                user.setEmailVerificationExpiresAt(LocalDateTime.now().plusMinutes(5));
                break;
            case AUTHENTICATOR_APP:
                logger.debug("2FA via authenticator app - no code sent, user generates their own");
                // For TOTP, we don't send codes - they're generated by the authenticator app
                break;
        }
        logger.info("2FA code sending process completed for user: {}", user.getEmail());
    }
    
    public boolean verifyEmailCode(User user, String code) {
        logger.debug("Verifying email code for user: {}", user.getEmail());
        boolean isValid = code != null && 
               code.equals(user.getEmailVerificationCode()) &&
               user.getEmailVerificationExpiresAt() != null &&
               user.getEmailVerificationExpiresAt().isAfter(LocalDateTime.now());
        logger.info("Email code verification result for user {}: {}", user.getEmail(), isValid);
        return isValid;
    }
    
    
    public boolean verifyTwoFactorCode(User user, String code) {
        logger.debug("Verifying 2FA code for user: {} using method: {}", user.getEmail(), user.getTwoFactorMethod());
        boolean result;
        switch (user.getTwoFactorMethod()) {
            case EMAIL:
                result = verifyEmailCode(user, code);
                break;
            case AUTHENTICATOR_APP:
                result = verifyTotpCode(user, code);
                break;
            default:
                logger.warn("Unknown 2FA method for user: {}", user.getEmail());
                result = false;
        }
        logger.info("2FA verification result for user {}: {}", user.getEmail(), result);
        return result;
    }
    
    public boolean verifyTotpCode(User user, String code) {
        logger.debug("Verifying TOTP code for user: {} using Authy-compatible verification", user.getEmail());
        
        if (user.getTwoFactorSecret() == null || code == null) {
            logger.warn("TOTP verification failed - missing secret or code for user: {}", user.getEmail());
            return false;
        }
        
        try {
            // Get current time step (30-second window)
            long currentTimeStep = System.currentTimeMillis() / 1000 / 30;
            
            // Check current, previous, and next time windows for clock drift tolerance
            for (int i = -1; i <= 1; i++) {
                String expectedCode = generateTotpCode(user.getTwoFactorSecret(), currentTimeStep + i);
                if (code.equals(expectedCode)) {
                    logger.info("TOTP code verification successful for user: {}", user.getEmail());
                    return true;
                }
            }
            
            logger.warn("TOTP code verification failed - no matching code found for user: {}", user.getEmail());
            return false;
        } catch (Exception e) {
            logger.error("TOTP code verification failed with exception for user: {} - Error: {}", user.getEmail(), e.getMessage());
            return false;
        }
    }
    
    private String generateTotpCode(String secret, long timeStep) {
        logger.debug("Generating TOTP code for time step: {} using Authy-compatible algorithm", timeStep);
        try {
            // Decode the base32 secret
            byte[] key = base32.decode(secret);
            
            // Convert time step to byte array (big-endian, 8 bytes)
            ByteBuffer buffer = ByteBuffer.allocate(8);
            buffer.putLong(timeStep);
            byte[] timeBytes = buffer.array();
            
            // Create HMAC-SHA1
            Mac mac = Mac.getInstance("HmacSHA1");
            SecretKeySpec secretKeySpec = new SecretKeySpec(key, "HmacSHA1");
            mac.init(secretKeySpec);
            
            // Calculate HMAC
            byte[] hash = mac.doFinal(timeBytes);
            
            // Dynamic truncation (RFC 4226)
            int offset = hash[hash.length - 1] & 0x0F;
            int binary = ((hash[offset] & 0x7F) << 24) |
                        ((hash[offset + 1] & 0xFF) << 16) |
                        ((hash[offset + 2] & 0xFF) << 8) |
                        (hash[offset + 3] & 0xFF);
            
            // Generate 6-digit code
            int code = binary % 1000000;
            String totpCode = String.format("%06d", code);
            
            logger.debug("TOTP code generated successfully: {}", totpCode);
            return totpCode;
        } catch (Exception e) {
            logger.error("Failed to generate TOTP code: {}", e.getMessage());
            return "000000";
        }
    }
    
    public void setupAuthenticatorApp(User user) {
        logger.info("Setting up authenticator app for user: {}", user.getEmail());
        if (user.getTwoFactorSecret() == null) {
            String secretKey = generateSecretKey();
            user.setTwoFactorSecret(secretKey);
            logger.info("Generated new secret key for authenticator app for user: {}", user.getEmail());
        } else {
            logger.info("Using existing secret key for authenticator app for user: {}", user.getEmail());
        }
    }
    
    public String getAuthenticatorAppQrCode(User user) {
        logger.info("Generating QR code for authenticator app for user: {}", user.getEmail());
        String secret = user.getTwoFactorSecret();
        String issuer = "Authentication Service";
        String accountName = user.getEmail();
        
        // Generate QR code URL for authenticator apps
        String qrCodeUrl = String.format("otpauth://totp/%s:%s?secret=%s&issuer=%s",
                issuer, accountName, secret, issuer);
        logger.info("QR code generated successfully for user: {}", user.getEmail());
        return qrCodeUrl;
    }
}
