package com.wilson.cmpe272.service;

import com.wilson.cmpe272.entity.User;
import org.apache.commons.codec.binary.Base32;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.security.SecureRandom;
import java.time.LocalDateTime;
import java.util.Random;

@Service
public class TwoFactorService {
    
    private static final Logger logger = LoggerFactory.getLogger(TwoFactorService.class);
    
    @Autowired
    private EmailService emailService;
    
    @Autowired
    private SmsService smsService;
    
    private final Random random = new Random();
    private final Base32 base32 = new Base32();
    
    public String generateVerificationCode() {
        String code = String.format("%06d", random.nextInt(1000000));
        logger.debug("Generated verification code: {}", code);
        return code;
    }
    
    public String generateSecretKey() {
        logger.debug("Generating secret key for authenticator app");
        byte[] buffer = new byte[10];
        new SecureRandom().nextBytes(buffer);
        String secretKey = base32.encodeToString(buffer).replaceAll("=", "");
        logger.debug("Secret key generated successfully");
        return secretKey;
    }
    
    public void sendEmailVerificationCode(User user) {
        logger.info("Sending email verification code to user: {}", user.getEmail());
        String verificationCode = generateVerificationCode();
        user.setEmailVerificationCode(verificationCode);
        user.setEmailVerificationExpiresAt(LocalDateTime.now().plusMinutes(10));
        
        emailService.sendVerificationCode(user.getEmail(), verificationCode);
        logger.info("Email verification code sent successfully to user: {}", user.getEmail());
    }
    
    public void sendPhoneVerificationCode(User user) {
        logger.info("Sending phone verification code to user: {} at phone: {}", user.getEmail(), user.getPhoneNumber());
        String verificationCode = generateVerificationCode();
        user.setPhoneVerificationCode(verificationCode);
        user.setPhoneVerificationExpiresAt(LocalDateTime.now().plusMinutes(10));
        
        smsService.sendVerificationCode(user.getPhoneNumber(), verificationCode);
        logger.info("Phone verification code sent successfully to user: {}", user.getEmail());
    }
    
    public void sendTwoFactorCode(User user) {
        logger.info("Sending 2FA code for user: {} using method: {}", user.getEmail(), user.getTwoFactorMethod());
        String verificationCode = generateVerificationCode();
        
        switch (user.getTwoFactorMethod()) {
            case EMAIL:
                logger.info("Sending 2FA code via email to user: {}", user.getEmail());
                emailService.sendTwoFactorCode(user.getEmail(), verificationCode);
                user.setEmailVerificationCode(verificationCode);
                user.setEmailVerificationExpiresAt(LocalDateTime.now().plusMinutes(5));
                break;
            case SMS:
                logger.info("Sending 2FA code via SMS to user: {} at phone: {}", user.getEmail(), user.getPhoneNumber());
                smsService.sendTwoFactorCode(user.getPhoneNumber(), verificationCode);
                user.setPhoneVerificationCode(verificationCode);
                user.setPhoneVerificationExpiresAt(LocalDateTime.now().plusMinutes(5));
                break;
            case AUTHENTICATOR_APP:
                logger.debug("2FA via authenticator app - no code sent, user generates their own");
                // For TOTP, we don't send codes - they're generated by the authenticator app
                break;
        }
        logger.info("2FA code sending process completed for user: {}", user.getEmail());
    }
    
    public boolean verifyEmailCode(User user, String code) {
        logger.debug("Verifying email code for user: {}", user.getEmail());
        boolean isValid = code != null && 
               code.equals(user.getEmailVerificationCode()) &&
               user.getEmailVerificationExpiresAt() != null &&
               user.getEmailVerificationExpiresAt().isAfter(LocalDateTime.now());
        logger.info("Email code verification result for user {}: {}", user.getEmail(), isValid);
        return isValid;
    }
    
    public boolean verifyPhoneCode(User user, String code) {
        logger.debug("Verifying phone code for user: {}", user.getEmail());
        boolean isValid = code != null && 
               code.equals(user.getPhoneVerificationCode()) &&
               user.getPhoneVerificationExpiresAt() != null &&
               user.getPhoneVerificationExpiresAt().isAfter(LocalDateTime.now());
        logger.info("Phone code verification result for user {}: {}", user.getEmail(), isValid);
        return isValid;
    }
    
    public boolean verifyTwoFactorCode(User user, String code) {
        logger.debug("Verifying 2FA code for user: {} using method: {}", user.getEmail(), user.getTwoFactorMethod());
        boolean result;
        switch (user.getTwoFactorMethod()) {
            case EMAIL:
                result = verifyEmailCode(user, code);
                break;
            case SMS:
                result = verifyPhoneCode(user, code);
                break;
            case AUTHENTICATOR_APP:
                result = verifyTotpCode(user, code);
                break;
            default:
                logger.warn("Unknown 2FA method for user: {}", user.getEmail());
                result = false;
        }
        logger.info("2FA verification result for user {}: {}", user.getEmail(), result);
        return result;
    }
    
    public boolean verifyTotpCode(User user, String code) {
        // This is a simplified TOTP verification
        // In a production environment, you would use a proper TOTP library
        // like Google Authenticator or Authy
        logger.debug("Verifying TOTP code for user: {}", user.getEmail());
        
        if (user.getTwoFactorSecret() == null || code == null) {
            logger.warn("TOTP verification failed - missing secret or code for user: {}", user.getEmail());
            return false;
        }
        
        try {
            long currentTime = System.currentTimeMillis() / 1000 / 30; // 30-second window
            
            // Generate codes for current and previous/next time windows
            for (int i = -1; i <= 1; i++) {
                String expectedCode = generateTotpCode(user.getTwoFactorSecret(), currentTime + i);
                if (code.equals(expectedCode)) {
                    logger.info("TOTP code verification successful for user: {}", user.getEmail());
                    return true;
                }
            }
            
            logger.warn("TOTP code verification failed - no matching code found for user: {}", user.getEmail());
            return false;
        } catch (Exception e) {
            logger.error("TOTP code verification failed with exception for user: {} - Error: {}", user.getEmail(), e.getMessage());
            return false;
        }
    }
    
    private String generateTotpCode(String secret, long time) {
        // This is a simplified implementation
        // In production, use a proper TOTP library
        logger.debug("Generating TOTP code for time window: {}", time);
        try {
            byte[] key = base32.decode(secret);
            byte[] timeBytes = new byte[8];
            for (int i = 7; i >= 0; i--) {
                timeBytes[i] = (byte) (time & 0xFF);
                time >>= 8;
            }
            
            // HMAC-SHA1 (simplified)
            String hash = java.security.MessageDigest.getInstance("SHA-1")
                    .digest((new String(key) + new String(timeBytes)).getBytes())
                    .toString();
            
            // Extract 6-digit code
            int offset = Integer.parseInt(hash.substring(hash.length() - 1), 16);
            String binary = Integer.toBinaryString(
                Integer.parseInt(hash.substring(offset * 2, offset * 2 + 8), 16)
            );
            
            String code = String.format("%06d", Integer.parseInt(binary) % 1000000);
            logger.debug("TOTP code generated successfully");
            return code;
        } catch (Exception e) {
            logger.error("Failed to generate TOTP code: {}", e.getMessage());
            return "000000";
        }
    }
    
    public void setupAuthenticatorApp(User user) {
        logger.info("Setting up authenticator app for user: {}", user.getEmail());
        if (user.getTwoFactorSecret() == null) {
            String secretKey = generateSecretKey();
            user.setTwoFactorSecret(secretKey);
            logger.info("Generated new secret key for authenticator app for user: {}", user.getEmail());
        } else {
            logger.info("Using existing secret key for authenticator app for user: {}", user.getEmail());
        }
    }
    
    public String getAuthenticatorAppQrCode(User user) {
        logger.info("Generating QR code for authenticator app for user: {}", user.getEmail());
        String secret = user.getTwoFactorSecret();
        String issuer = "Authentication Service";
        String accountName = user.getEmail();
        
        // Generate QR code URL for authenticator apps
        String qrCodeUrl = String.format("otpauth://totp/%s:%s?secret=%s&issuer=%s",
                issuer, accountName, secret, issuer);
        logger.info("QR code generated successfully for user: {}", user.getEmail());
        return qrCodeUrl;
    }
}
